export const PRODUCT_LIST_REQ = "PRODUCT_LIST_REQUEST";
export const PRODUCT_LIST_REQ_SUCCESS = "PRODUCT_LIST_SUCCESS";
export const PRODUCT_LIST_REQ_FAIL = "PRODUCT_LIST_FAIL";

export const PRODUCT_DETAIL_REQ = "PRODUCT_LIST_REQUEST";
export const PRODUCT_DETAIL_REQ_SUCCESS = "PRODUCT_LIST_SUCCESS";
export const PRODUCT_DETAIL_REQ_FAIL = "PRODUCT_LIST_FAIL";
